apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
  labels:
    app: pet-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-1
  template:
    metadata:
      labels:
        app: pet-1
    spec:
      containers:
      - name: pet-1-container
        image: 975050294800.dkr.ecr.us-east-1.amazonaws.com/petclinic2:{{ .Values.image.tag}}
        ports:
        - containerPort: 8080
